### ISSUE TITLE
Merging upstream

### ISSUE THREAD

**Issue by gregadams4** [opendoor-labs/gozw#39]
Hey guys,

See you have done a lot of work on the library, how would you feel about merging your changes upstream?

**Comment by parrotmac** [comment]
Hey Greg!

I’m happy to help merge any of this upstream.

**Comment by lukescott** [comment]
Hey @parrotmac, I would like this as well! Would you guys like to take over maintaining the repo?

A bit of back story:

It was originally written by @bjyoungblood. My goal for creating the repo was to pull the efforts of the Go Z-Wave community together behind a single project. At the time @stamp was working on https://github.com/stampzilla/gozwave and noted that he liked Ben's approach of generating command classes rather than doing everything by hand.

I made some initial attempts to clean up the generation code, but like the others found I did not have a lot of time to commit to the project. I also use openzwave at home, and felt I hadn't reached a point where I could switch everything over.

I know that my co-worker @asherry99 actively uses gozw at home (in particular this fork), so he is more knowledgeable and works on it more than I do in his spare time. Although both of us are kept quite busy at our days jobs.

**Comment by parrotmac** [comment]
Hey @lukescott! Sorry for the very late reply on this. We're no longer using this repository/code, so I don't think @opendoor-labs is the right home for this project. However, on a personal side note, I'd be happy to help out with @gozwave/gozw. As mentioned in #40 we're reachable for further discussion on the #gozwave Gophers channel 🙂
